using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[Virtual]
[GenerateTypedNameReferences]
public partial class PdaWindow : BaseWindow
{

    public string? BorderColor
    {
        get => Background.ActualModulateSelf.ToHex();

        set => Background.ModulateSelfOverride = Color.FromHex(value, Color.White);
    }

    public string? AccentHColor
    {
        get => AccentH.ActualModulateSelf.ToHex();

        set
        {
            AccentH.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentH.Visible = value != null;
        }
    }

    public string? AccentVColor
    {
        get => AccentV.ActualModulateSelf.ToHex();

        set
        {
            AccentV.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentV.Visible = value != null;
        }
    }

    private const int DRAG_MARGIN_SIZE = 7; // DS14

    public PdaWindow()
    {
        RobustXamlLoader.Load(this);

        CloseButton.OnPressed += _ => Close();
        XamlChildren = ContentsContainer.Children;

        AccentH.Visible = false;
        AccentV.Visible = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        // DS14-start
        var mode = DragMode.Move;

        if (Resizable)
        {
            if (relativeMousePos.Y < DRAG_MARGIN_SIZE)
                mode = DragMode.Top;
            else if (relativeMousePos.Y > Size.Y - DRAG_MARGIN_SIZE)
                mode = DragMode.Bottom;

            if (relativeMousePos.X < DRAG_MARGIN_SIZE)
                mode |= DragMode.Left;
            else if (relativeMousePos.X > Size.X - DRAG_MARGIN_SIZE)
                mode |= DragMode.Right;
        }

        return mode;
        // DS14-end
    }
}
